### ISSUE TITLE
Issue: Cannot find firebase

### ISSUE THREAD

**Issue by mahee522** [ProgramWithCode/Client-panel-in-Angular-4#1]
Hi,
After learning angular4 basics I have gone through this project videos thank you for keeping this project in git.I imported this project in eclipse.
After running `npm install` at project root level I did `ng build` but it is giving me below errors

Please help me on this

`ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (12,23): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (13,26): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (14,26): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (15,35): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (77,40): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (78,41): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (79,37): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/interfaces.d.ts (82,28): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/app/firebase.app.module.d.ts (5,45): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/app/firebase.app.module.d.ts (8,17): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/app/firebase.app.module.d.ts (9,21): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/app/firebase.app.module.d.ts (10,22): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/app/firebase.app.module.d.ts (11,20): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/app/firebase.app.module.d.ts (12,19): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/@firebase/database/dist/esm/src/core/AuthTokenProvider.d.ts (17,39): Cannot find module '@firebase/app-types/private'.
ERROR in /Client-panel-in-Angular-4/node_modules/@firebase/database/dist/esm/src/api/Database.d.ts (4,33): Cannot find module '@firebase/app-types/private'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_list_observable.d.ts (8,50): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_list_observable.d.ts (8,80): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_list_observable.d.ts (13,21): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_list_observable.d.ts (14,53): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_list_observable.d.ts (15,39): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_list_observable.d.ts (16,83): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_object_observable.d.ts (8,11): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_object_observable.d.ts (9,102): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_object_observable.d.ts (11,22): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_object_observable.d.ts (12,28): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/database/firebase_object_observable.d.ts (13,15): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/auth/auth.d.ts (7,11): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/auth/auth.d.ts (8,27): Cannot find namespace 'firebase'.
ERROR in /Client-panel-in-Angular-4/node_modules/angularfire2/auth/auth.d.ts (11,83): Cannot find namespace 'firebase'.`

**Comment by DeepLinkNode** [comment]
Duplicate this :-  https://stackoverflow.com/questions/39118836/angularfire2-cannot-find-namespace-firebase
